apiVersion: apps/v1
kind: Deployment
metadata:
  name: mspl-ecommerce
  labels:
    app: mspl-ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mspl-ecommerce
  template:
    metadata:
      labels:
        app: mspl-ecommerce
    spec:
      containers:
        - name: mspl-ecommerce
          image: fileweb1:v1  # Update with your image path if using a registry
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
      imagePullSecrets:
        - name: mydocker  # Reference your Docker secret here
---
apiVersion: v1
kind: Service
metadata:
  name: mspl-ecommerce-service
spec:
  selector:
    app: mspl-ecommerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
